<?php

 $apiKey = "rzp_live_O6Kv5jdInd11fs";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="200" // 160Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $_POST['oid'];?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="BIAS"
    data-description="Bhimtal Adventures "
    data-image="https://www.eduvidya.com/admin/Upload/Institutes/637020139950004623_Birla%20Institute%20of%20Applied%20Sciences.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['phone'];?>"
    data-theme.color="#222222"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">

</form>


<style>
    .razorpay-payment-button{
        display:none;
    }
</style>

<script>
    $(document).ready(function(){
       
       $('.razorpay-payment-button').click();
        
    });
</script>